# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Curso de Electricidad y Magnetismo
author: José Miguel Pinto
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Información del repositorio (NECESARIO para que Colab encuentre tus archivos)
repository:
  url: https://github.com/jmpintog1/libro-fisica-vivo  # La URL de tu repo
  path_to_book: "."  # Donde está el libro (raíz)
  branch: main  # La rama principal

# Configuración de los botones de lanzamiento
launch_buttons:
  notebook_interface: "classic" 
  colab_url: "https://colab.research.google.com"
  # Muestra el botón de Colab
  colab: true

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
